FROM python:3.9

WORKDIR /app

COPY ./requirements.txt .

RUN pip3 install -r requirements.txt
RUN pip3 install Flask gunicorn

COPY . .

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]